### PR TITLE
GitHub Action to lint Python code

### PR DESCRIPTION
**Pull request by cclauss**
To try out automated testing with GitHub Actions on your own repo before doing so on https://github.com/Komodo/KomodoEdit

### CODE REVIEW

**Comment by th3coop** [comment]
@cclauss thanks for this.  I've not used Github Actions yet.  Looking at it on your fork it looks like the Action failed due to bad YAML.  Do you know why that is?  The YAML looks fine to me so I'm assuming it's something specific to Github.

**Comment by cclauss** [comment]
Sorry about this.  It was an indentation error.  https://github.com/cclauss/Elf-Mania/commit/68d357307f1a9824ffe8d25d6e618ea3d3f85b1f/checks?check_suite_id=391274781

**Comment by th3coop** [comment]
@cclauss, thank you kindly.  Very cool btw.  So this will run on every push to the repo?

**Review by th3coop — APPROVED** [review]

**Comment by cclauss** [comment]
Every push and every pull request
https://github.com/th3coop/Elf-Mania/blob/master/.github/workflows/lint_python.yml#L2

**Comment by th3coop** [comment]
Very cool.  Thanks again @cclauss.

**Pull request merged**
